services:
  projects-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=projects_api
      - FLASK_ENV=development
      - CONFIG_PATH=config/development.yaml
    volumes:
      - ./config:/app/config
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
